"""empty message

Revision ID: 4c3751486e7e
Revises: 
Create Date: 2020-04-13 12:08:39.305586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c3751486e7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=120), nullable=False),
    sa.Column('tone', sa.String(length=50), nullable=False),
    sa.Column('dictionaryId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dictionaryId'], ['dictionary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    op.drop_table('dictionary')
    # ### end Alembic commands ###
