"""empty message

Revision ID: 69de8fc4cd20
Revises: 4c3751486e7e
Create Date: 2020-04-13 19:03:24.938189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69de8fc4cd20'
down_revision = '4c3751486e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('part_of_speech', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word', 'part_of_speech')
    # ### end Alembic commands ###
