"""empty message

Revision ID: 78f4d0125f95
Revises: 69de8fc4cd20
Create Date: 2020-04-13 19:37:18.613766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f4d0125f95'
down_revision = '69de8fc4cd20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word', 'part_of_speech')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('part_of_speech', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
