"""empty message

Revision ID: 9444579c0c2a
Revises: 4c3751486e7e
Create Date: 2020-04-13 15:14:04.347173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9444579c0c2a'
down_revision = '4c3751486e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('part_of_speech', sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word', 'part_of_speech')
    # ### end Alembic commands ###
